### PR TITLE
nicenicks plugin (nick coloring without collisions)

### PR DESCRIPTION
**Pull request by epitron**
People have been asking me to put my nick colouring in an easier-to-find place.

This place looks pretty good!

### CODE REVIEW

**Comment by Burrito-Bazooka** [comment]
Thank you, I've been wanting this for a while! Once I resorted to editing Hexchat's source to add more colours to its list of colours it uses on nicks, but this was unwieldy with updating. I think it was [this line](/hexchat/hexchat/blob/78486b49d5b688ba5054631b849f8959846cf07b/src/common/text.c#L1960).

**Comment by Burrito-Bazooka** [comment]
Two issues:

* My client is set so that the channels change colours when there is a message or a status change (like someone joining or parting). Status changes are green, messages are red. That's the expected behaviour. The current behaviour is all messages result in a green colour, and this didn't happen before I enabled the script (it behaved as expected). It's as if all messages are now status changes.

* Freenode is a bit special in that it prefixes all messages with "+" or "-". I thought that this depended on whether a user was identified with NickServ, but in my testing, this didn't match up. Freenode expects the client to strip this away, I think. Hexchat strips this away somehow, but they now appear if the plugin is enabled.

I would have looked into this more if I had time... I'll have time again tomorrow, I think. Thanks again for publishing :)

**Comment by epitron** [comment]
Full disclosure: I wrote this script over 10 years ago, and haven't touched it since. I haven't used X-Chat in ages -- I decided to contribute it to `hexchat-addons` because somene emailed me saying it was really hard to find.

I'm not surprised that "Channel Status Colour" is weird; X-Chat (in 2004) didn't let you set the colours of nicks, so I had to simulate regular channel messages by using [xchat.prnt](https://labix.org/xchat-python#head-918e19d7e9e02e4d1fa42b6814e8404e4e3c3c16), which is a general-purpose way of printing text into an X-Chat buffer.

Would you be interested in fixing these two problems? I'm not sure how to fix the status colours, but the nick thing can be fixed by just stripping the first character off of the nick if it's `-` or `+`.

**Comment by Burrito-Bazooka** [comment]
> Would you be interested in fixing these two problems?

I would, and I'll definitely have a go this weekend, if not later today.

**Comment by epitron** [comment]
Excellent!

**Comment by TingPing** [comment]
@epitron Could you give it a license?

**Comment by epitron** [comment]
Hah, sure. I put everything under the WTFPL, so I'll just add a comment.

**Pull request merged**
